#!/usr/bin/env python3
"""Render a test-coverage SVG for the README: how many tests each module has.

Counts are taken from pytest's own collection (authoritative), falling back to
counting `def test_` if pytest is not importable. One bar per test file,
labelled by the module or area it covers, sorted by count. The point is to show
at a glance that every module carries a test harness.

    python3 tools/render_test_coverage_svg.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# test file stem -> human label for the module / area it exercises
LABELS = {
    "test_resolver": "resolver (conflict + lineage)",
    "test_store": "store (the ledger)",
    "test_export": "export (AGENTS / DECISIONS)",
    "test_watch": "watch (streaming gate)",
    "test_mod": "mod (supersede / retire)",
    "test_capture": "capture",
    "test_collab": "collab (execution governance)",
    "test_gate": "gate (runtime enforcement)",
    "test_config_doctor_docs": "config / doctor / docs",
    "test_integrity_gaps": "integrity internals",
    "test_integrity": "integrity (attest + verify)",
    "test_why_inherit_defer": "why / inherit / defer",
    "test_discord_sensor": "discord sensor",
    "test_check_find_stats": "check / find / stats",
    "test_dynamics": "dynamics (lenses)",
    "test_craft_audit": "craft (audit)",
    "test_integrations": "integrations (obsidian / mempalace)",
    "test_slack_integrations": "slack integration",
    "test_guard": "guard (pre-commit hook)",
    "test_demo": "demo",
    "test_bootstrap": "bootstrap",
    "test_figma_bridge": "figma bridge",
    "test_attest": "attestation (RFC 3161)",
    "test_evidence_attest": "evidence attestation",
    "test_entrypoints_smoke": "mcp / api entrypoints",
}


def counts() -> dict[str, int]:
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-q"],
            cwd=ROOT, capture_output=True, text=True, timeout=300,
        )
        c: Counter[str] = Counter()
        for line in out.stdout.splitlines():
            m = re.match(r"tests/(test_[a-z0-9_]+)\.py::", line)
            if m:
                c[m.group(1)] += 1
        if c:
            return dict(c)
        print("pytest collected nothing; falling back", file=sys.stderr)
    except Exception as e:  # pytest not available
        print(f"pytest collect failed ({e}); falling back to def-test count", file=sys.stderr)
    c2: Counter[str] = Counter()
    for p in sorted((ROOT / "tests").glob("test_*.py")):
        c2[p.stem] = len(re.findall(r"^\s*def test_", p.read_text(encoding="utf-8"), re.M))
    return dict(c2)


def esc(s: str) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render(data: dict[str, int]) -> str:
    rows = sorted(data.items(), key=lambda kv: (-kv[1], LABELS.get(kv[0], kv[0])))
    total = sum(v for _, v in rows)
    n_mod = len(rows)
    maxc = max((v for _, v in rows), default=1)

    W = 820
    PAD_T, ROW, BAR_H = 92, 21, 13
    LABEL_X, BAR_X0 = 260, 268
    BAR_MAX = 470  # px for the largest bar; count label sits just after
    H = PAD_T + len(rows) * ROW + 40

    p = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'font-family="ui-sans-serif,system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif" '
        f'role="img" aria-label="Test coverage by module">',
        f'<rect x="0" y="0" width="{W}" height="{H}" rx="14" fill="#ffffff" stroke="#E4E8EF"/>',
        f'<text x="34" y="44" font-size="21" font-weight="700" fill="#0F172A">Test coverage</text>',
        f'<text x="34" y="67" font-size="12.5" fill="#5B6675">'
        f'<tspan font-weight="700" fill="#2745B8">{total} tests</tspan> across {n_mod} modules. '
        f'Every module carries a harness.</text>',
    ]
    for i, (stem, cnt) in enumerate(rows):
        y = PAD_T + i * ROW
        cy = y + ROW / 2
        w = max(2.0, cnt / maxc * BAR_MAX)
        label = LABELS.get(stem, stem.replace("test_", "").replace("_", " "))
        p.append(f'<text x="{LABEL_X - 8}" y="{cy + 3.5:.1f}" font-size="11" text-anchor="end" fill="#3B4553">{esc(label)}</text>')
        p.append(f'<rect x="{BAR_X0}" y="{cy - BAR_H/2:.1f}" width="{w:.1f}" height="{BAR_H}" rx="3" fill="#4A90D9"/>')
        p.append(f'<text x="{BAR_X0 + w + 7:.1f}" y="{cy + 3.5:.1f}" font-size="10.5" fill="#5B6675" font-weight="600">{cnt}</text>')

    p.append(f'<text x="{W - 30}" y="{H - 16}" font-size="10" text-anchor="end" fill="#AAB2BF" '
             f'font-family="ui-monospace,SFMono-Regular,Menlo,monospace">counted from pytest, regenerated by CI</text>')
    p.append("</svg>")
    return "\n".join(p) + "\n"


def main() -> int:
    data = counts()
    if not data:
        print("no test data found", file=sys.stderr)
        return 1
    svg = render(data)
    if "—" in svg:
        print("WARNING: em dash present", file=sys.stderr)
    out = ROOT / "assets" / "test-coverage.svg"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(svg, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {sum(data.values())} tests, {len(data)} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
